scrape_configs:
  - job_name: "bank-transactions"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 3s # how often to scrape
    static_configs:
      - targets:
        - "host.docker.internal:8080"
